# Generated by Django 4.2.1 on 2023-05-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booked_on",
            field=models.DateField(auto_now=True),
        ),
    ]
