# Generated by Django 4.2.1 on 2023-05-20 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siteapp", "0002_booking_booked_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="appointment_time",
        ),
    ]
